#!/bin/env python3
import sys
import yaml
import json
import copy

# Initialize an empty list to collect lines
input_lines = []

for line in sys.stdin:
  # Collect the lines
  input_lines.append(line)

# Join the collected lines into a single string
yaml_input = ''.join(input_lines)

try:
  # Parse the entire YAML input
  #data1 = json.loads(yaml_input)
  #print(data1)
  data = yaml.safe_load(yaml_input)[0]
  
  #
  #print(data)
  if data is not None:
    
    data['energy']=1
    print(data)
    for output in data:
      pass
      
    #   imp = copy.deepcopy(output)
    #   imp['energy'] = 1
    #   data['outputs'].append(imp)
    #print(yaml.dump(data, default_flow_style=False))
  else:
    print("No valid YAML input provided.")

  
except yaml.YAMLError as e:
  print("Error parsing YAML:", e)
